---
abstract: 'A JSON-RPC 2.0 server.'
author:
  - 'JT Smith <RIZEN@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JSON-RPC-Dispatcher
no_index:
  directory:
    - author.t
    - eg
requires:
  JSON: 2.16
  Log::Any: 0.11
  Moose: 0.93
  Plack: 0.9913
  Test::More: 0
version: 0.0400
